In [1]:
import json
import os
import pandas as pd
import zipfile

In [2]:
!kaggle datasets download "dnpdatasetstudio/dataset-um-pub"

dataset-um-pub.zip: Skipping, found more recently modified local copy (use --force to force download)

In [3]:
z = zipfile.ZipFile('dataset-um-pub.zip', 'r')

In [4]:
json_path = z.extract('UM_dataset.json')

try:
    with open(json_path, "r") as f:
        data_obj = json.load(f)
        
except:
    logger.exception(f"Error loading {json_path}!")

In [5]:
df = pd.DataFrame()

In [6]:
for tracker in data_obj.keys():
    for date in data_obj[tracker]:
        for ticker_date in data_obj[tracker][date]:
            df = df.append(ticker_date, ignore_index=True)

In [7]:
df

,date,portfolio_id,sector_amount,sp500index_atclose,ticker,ticker_bench,ticker_lot,ticker_price,ticker_sector,ticker_sizemultiplier
0,2021-04-20,609,11.8116,412.1700,AAPL,52.4300,0,133.1100,Technology,137.3000
1,2021-04-20,609,4.6711,412.1700,ABMD,64.5600,0,330.1000,Healthcare,149.4300
2,2021-04-20,609,5.2310,412.1700,ADP,-8.0900,0,192.8100,Industrials,76.7800
3,2021-04-20,609,5.2310,412.1700,ALB,106.9200,0,148.5200,Industrials,191.7900
4,2021-04-20,609,11.8116,412.1700,ATVI,-17.5800,0,94.4700,Technology,67.2900
...,...,...,...,...,...,...,...,...,...,...
496,2021-05-06,609,12.8490,418.3300,TMUS,-19.7000,0,127.1200,Technology,67.9300
497,2021-05-06,609,6.8207,418.3300,TPR,121.5400,0,32.7100,Consumer Cyclical,209.1700
498,2021-05-06,609,6.8207,418.3300,TSCO,-13.9900,0,135.5400,Consumer Cyclical,73.6400
499,2021-05-06,609,12.8490,418.3300,TWTR,1.0700,0,46.5900,Technology,88.7000
500,2021-05-06,609,6.5885,418.3300,WFC,-30.8800,0,39.5800,Financial,56.7500